<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>GUI</RootNamespace>
    <AssemblyName>HebiKaioPokedex</AssemblyName>
    <Version>0.1.0</Version>
    <Product>HebiKaio Pokedex</Product>
    <Company>HebiKaio</Company>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon />
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/HebiKaio.Core/HebiKaio.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../data/p5e/*.json" Link="data/p5e/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
